[supervisord]
nodaemon=true
logfile=/dev/null
pidfile=/tmp/supervisord.pid
loglevel=info
user=root

[program:php-fpm]
command=php-fpm --fpm-config /docker/php-fpm.conf
autostart=true
autorestart=true
priority=10
startsecs=3
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:nginx]
command=nginx -c /tmp/nginx.conf -g "daemon off;"
autostart=true
autorestart=true
priority=20
startretries=5
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:queue]
command=php /app/artisan queue:work --sleep=3 --tries=3 --max-time=3600 --queue=default
autostart=true
autorestart=true
priority=30
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
